//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursavayaAnna
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип занятости.
    /// </summary>
    // *** Start programmer edit section *** (ТипЗанятости CustomAttributes)

    // *** End programmer edit section *** (ТипЗанятости CustomAttributes)
    public enum ТипЗанятости
    {
        
        // *** Start programmer edit section *** (ТипЗанятости.Отгул CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Отгул CustomAttributes)
        [Caption("Отгул")]
        Отгул,
        
        // *** Start programmer edit section *** (ТипЗанятости.Работал CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Работал CustomAttributes)
        [Caption("Работал")]
        Работал,
        
        // *** Start programmer edit section *** (ТипЗанятости.Прогул CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Прогул CustomAttributes)
        [Caption("Прогул")]
        Прогул,
        
        // *** Start programmer edit section *** (ТипЗанятости.Болел CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Болел CustomAttributes)
        [Caption("Болел")]
        Болел,
        
        // *** Start programmer edit section *** (ТипЗанятости.Отпуск CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Отпуск CustomAttributes)
        [Caption("Отпуск")]
        Отпуск,
        
        // *** Start programmer edit section *** (ТипЗанятости.Выходной CustomAttributes)

        // *** End programmer edit section *** (ТипЗанятости.Выходной CustomAttributes)
        [Caption("Выходной")]
        Выходной,
    }
}
