//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursavayaAnna
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуги мастера.
    /// </summary>
    // *** Start programmer edit section *** (УслугиМастера CustomAttributes)

    // *** End programmer edit section *** (УслугиМастера CustomAttributes)
    [AutoAltered()]
    [Caption("Услуги мастера")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугиМастераE", new string[] {
            "Услуга as \'Услуга\'",
            "Услуга.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Услуга.Наименование"})]
    [MasterViewDefineAttribute("УслугиМастераE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class УслугиМастера : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.KursavayaAnna.Услуга fУслуга;
        
        private IIS.KursavayaAnna.сотрудник fсотрудник;
        
        // *** Start programmer edit section *** (УслугиМастера CustomMembers)

        // *** End programmer edit section *** (УслугиМастера CustomMembers)

        
        /// <summary>
        /// Услуги мастера.
        /// </summary>
        // *** Start programmer edit section *** (УслугиМастера.Услуга CustomAttributes)

        // *** End programmer edit section *** (УслугиМастера.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.KursavayaAnna.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (УслугиМастера.Услуга Get start)

                // *** End programmer edit section *** (УслугиМастера.Услуга Get start)
                IIS.KursavayaAnna.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (УслугиМастера.Услуга Get end)

                // *** End programmer edit section *** (УслугиМастера.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УслугиМастера.Услуга Set start)

                // *** End programmer edit section *** (УслугиМастера.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (УслугиМастера.Услуга Set end)

                // *** End programmer edit section *** (УслугиМастера.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KursavayaAnna.сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (УслугиМастера.сотрудник CustomAttributes)

        // *** End programmer edit section *** (УслугиМастера.сотрудник CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "сотрудник"})]
        public virtual IIS.KursavayaAnna.сотрудник сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (УслугиМастера.сотрудник Get start)

                // *** End programmer edit section *** (УслугиМастера.сотрудник Get start)
                IIS.KursavayaAnna.сотрудник result = this.fсотрудник;
                // *** Start programmer edit section *** (УслугиМастера.сотрудник Get end)

                // *** End programmer edit section *** (УслугиМастера.сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УслугиМастера.сотрудник Set start)

                // *** End programmer edit section *** (УслугиМастера.сотрудник Set start)
                this.fсотрудник = value;
                // *** Start programmer edit section *** (УслугиМастера.сотрудник Set end)

                // *** End programmer edit section *** (УслугиМастера.сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугиМастераE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиМастераE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиМастераE", typeof(IIS.KursavayaAnna.УслугиМастера));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of УслугиМастера.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУслугиМастера CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУслугиМастера CustomAttributes)
    public class DetailArrayOfУслугиМастера : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KursavayaAnna.DetailArrayOfУслугиМастера members)

        // *** End programmer edit section *** (IIS.KursavayaAnna.DetailArrayOfУслугиМастера members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УслугиМастера by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УслугиМастера.
        /// </summary>
        public DetailArrayOfУслугиМастера(IIS.KursavayaAnna.сотрудник fсотрудник) : 
                base(typeof(УслугиМастера), ((ICSSoft.STORMNET.DataObject)(fсотрудник)))
        {
        }
        
        public IIS.KursavayaAnna.УслугиМастера this[int index]
        {
            get
            {
                return ((IIS.KursavayaAnna.УслугиМастера)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KursavayaAnna.УслугиМастера dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
